version: "3.7"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_anunbis
    volumes:
      - ./mysql:/var/lib/mysql_anunbis
    expose: 
      - "3306"
    command: --default-authentication-plugin=mysql_native_password