version: "3.7"
services:
  flask:
      build:
        ./
      depends_on:
        - mysql
      ports:
        - "5000:5000"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_anunbis
    volumes:
      - ./mysql:/var/lib/mysql_anunbis
    expose: 
      - "3306"
    command: --default-authentication-plugin=mysql_native_password