site_name: MDS-2020-2-G5
site_description: Repositório do Grupo 05
repo_url: https://github.com/fga-eps-mds/MDS-2020-2-G5.git

theme:
    name: 'material'
    palette:
        primary: 'black'
        accent: 'amber'
    features:
        navigation.tabs

plugins:
    - search

nav:
    - Início: "index.md"
    - Sprints:
        - Sprint 0:
            - Planejamento: sprints/planejamento-sprint-0.md
            - Revisão: sprints/revisao-sprint-0.md
        - Sprint 1:
            - Planejamento: sprints/planejamento-sprint-1.md
            - Revisão: sprints/revisao-sprint-1.md
        - Sprint 2:
            - Planejamento: sprints/planejamento-sprint-2.md
            - Revisão: sprints/revisao-sprint-2.md
    - Projeto:
            - Documento de Visão: documentacao/documento-de-visao.md
            - Documento de Arquitetura: documentacao/documento-de-arquitetura.md
            - Roadmap: documentacao/roadmap.md
            - Termo de Abertura: documentacao/termo-de-abertura.md
    - Produto: 
        - Backlog do Produto: produto/backlog.md